icingtales/icingtales/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopping.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

icingtales/shopping/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static

app_name = "shopping"
urlpatterns = [
    path('', views.index_view, name='index'),
    path('register', views.register_view, name='register'),
    path('sign-in', views.signin_view, name='signin'),
    path('sign-out', views.signout_view, name='signout'),
    path('admin-panel', views.admin_view, name='admin'),
    path('products', views.products_view, name='products'),
    path('users', views.users_view, name='users'),
    path('aboutus', views.aboutus_view, name='aboutus'),
    path('sitemap', views.sitemap_view, name='sitemap'),
    path('search', views.search_view, name='search'),
    path('products/add', views.add_product_view, name='addproduct'),
    path('products/update/<int:id>', views.update_product_view, name='updateproduct'),
    path('order/add', views.add_order_view, name='addorder'),
    path('order/update/<int:id>', views.update_order_view, name='updateorder'),
    path('category/<str:category>', views.category_view, name="category"),
    path('flavor/<str:flavor>', views.flavor_view, name='flavor'),
    path('topping/<str:topping>', views.topping_view, name='topping'),
    path('flower/<str:flower>', views.flower_view, name='flower'),
    path('item/<int:id>', views.item_view, name="item"),
    path('profile/<int:id>', views.profile_view, name="profile"),
    path('profile/<int:id>/update', views.update_profile_view, name="updateprofile"),
    path('cart/<int:id>', views.cart_view, name="cart"),
    path('add-to-cart/<int:item_id>', views.add_to_cart_view, name='add_to_cart'),
    path('delete-cart-item/<int:id>', views.delete_cart_item_view, name='delete_cart_item'),
    path('empty-cart/<int:id>', views.empty_cart_view, name='empty_cart'),
    path('checkout/<int:id>', views.checkout_view, name='checkout'),
    path('process-payment/<int:order_id>', views.process_payment, name='process_payment'),
    path('payment-done/<int:order_id>', views.payment_done, name='payment_done'),
    path('payment-cancelled/<int:order_id>', views.payment_canceled, name='payment_cancelled'),
    path('purchases/<int:id>', views.purchases_view, name='purchases'),
    path('receipt/<int:order_id>', views.receipt_view, name='receipt'),
    path('receipt/<int:order_id>/pdf', views.generate_PDF_view, name='pdf_receipt'),
    path('toppings', views.toppings_view, name='admin_toppings'),
    path('flavors', views.flavors_view, name='admin_flavors'),
    path('flowers', views.flowers_view, name='admin_flowers'),
    path('toppings/add', views.add_topping_view, name='addtopping'),
    path('flavors/add', views.add_flavor_view, name='addflavor'),
    path('flowers/add', views.add_flower_view, name='addflower'),
    path('toppings/update/<int:id>', views.update_topping_view, name='updatetopping'),
    path('flavors/update/<int:id>', views.update_flavor_view, name='updateflavor'),
    path('flowers/update/<int:id>', views.update_flower_view, name='updateflower'),
    path('admin-panel/order/delete/<int:id>', views.delete_order_view, name='deleteorder'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

icingtales/shopping/views.py
import os
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required, user_passes_test
from django.views.decorators.csrf import csrf_exempt
from django.forms.models import modelformset_factory
from django.core.mail import send_mail
from django.template.loader import render_to_string, get_template
from django.template import Context
from xhtml2pdf import pisa
from xhtml2pdf.config.httpconfig import httpConfig
from django.utils.html import strip_tags
from django.conf import settings
from decimal import Decimal
from paypal.standard.forms import PayPalPaymentsForm
from django.core import serializers
from django.http import JsonResponse
from datetime import date
from .models import *
from .analytics.analytics import *
from shopping.froms import *
from shopping.utils import *


# Create your views here.
@user_passes_test(lambda u: not (u.is_superuser or u.is_staff), login_url='/sign-in')
def index_view(request):
    if request.user.is_authenticated:
        return render(request, 'shopping/index.html', {
            'first_name': request.user.get_short_name(),
            'banner': Banner.objects.first().image,
            'items' : Item.objects.all(),
            'recommended': get_recommended_items(request.user.id)
        })
    return render(request, 'shopping/index.html', {
        'banner': Banner.objects.first().image,
        'items': Item.objects.all()
    })

@user_passes_test(lambda u: not (u.is_superuser or u.is_staff), login_url='/sign-in')
def register_view(request):
    if request.user.is_authenticated:
        logout(request)
    form = RegistrationForm()
    all_users = User.objects.all()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            gender = form.cleaned_data['gender']
            email = form.cleaned_data['email']
            mobile_number = form.cleaned_data['mobile_number']
            date_of_birth = form.cleaned_data['date_of_birth']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            if not password1 == password2:
                return render(request, 'shopping/register.html', {
                    'message': 'Password does not match password confirmation',
                    'form': form
                })
            try:
                user = all_users.get(email=email)
                return render(request, 'shopping/register.html', {
                    'message': 'Account already exists with the email',
                    'form': form
                })
            except User.DoesNotExist:
                pass
            try:
                user = all_users.get(mobile_number=mobile_number)
                return render(request, 'shopping/register.html', {
                    'message': 'Account already exists with the mobile number',
                    'form': form
                })
            except:
                pass

            user = User.objects.create_user(first_name=first_name,
                                            last_name=last_name,
                                            gender=gender,
                                            username=email,
                                            email=email,
                                            mobile_number=mobile_number,
                                            date_of_birth=date_of_birth,
                                            password=password1,
                                            )
            user.save()
            profile = Profile(user=user)
            profile.save()
            login(request, user, backend="django.contrib.auth.backends.ModelBackend")
            return HttpResponseRedirect(reverse('shopping:index'))
        return render(request, 'shopping/register.html', {
            'form': form
        })
    return render(request, 'shopping/register.html', {
        'form': form
    })

def signin_view(request):
    form = SignInForm()
    if request.method == 'POST':
        form = SignInForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request=request, email=email, password=password)
            if user is not None:
                if user.is_superuser or user.is_staff:
                    login(request, user)
                    return HttpResponseRedirect(reverse('shopping:admin'))
                else:
                    login(request, user, backend="shopping.EmailAuthenticationBackend.EmailBackend")
                    return HttpResponseRedirect(reverse('shopping:index'))

        return render(request, 'shopping/signin.html', {
            'form': SignInForm(),
            'message': 'Invalid email and/or password.'
        })
    return render(request, 'shopping/signin.html', {
        'form': form
    })

def signout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('shopping:index'))

@staff_member_required(login_url='/sign-in')
@login_required(login_url='/sign-in')
def admin_view(request):
    order_status = dict(Order.STATUS_CHOICES)
    #orders = [[getattr(ins, name) for name in field_names] for ins in model.objects.prefetch_related().all()]
    orders = Order.objects.all()

    return render(request, 'shopping/admin.html', {
        'user': request.user,
        'total_orders': Order.objects.count(),
        'total_orders_today': Order.objects.filter(date_created__gte=date.today()).count(),
        'total_orders_pending': Order.objects.filter(status='P').count(),
        'total_orders_ready': Order.objects.filter(status='R').count(),
        'orders': orders.order_by('-date_created'),
        'order_status': order_status
    })

@staff_member_required(login_url='/sign-in')
@login_required(login_url='/sign-in')
def products_view(request):
    return render(request, 'shopping/products.html', {
        'items': Item.objects.all(),
    })
@staff_member_required(login_url='/sign-in')
@login_required(login_url='/sign-in')
def add_product_view(request):
    form = ItemCreationForm()
    image_form = ImageFormset(queryset=ItemImage.objects.none())
    if request.method == 'POST':
        form = ItemCreationForm(request.POST)
        image_form = ImageFormset(request.POST, request.FILES)
        if form.is_valid() and image_form.is_valid():
            item = form.save()
            for form in image_form:
                image = form.save(commit=False)
                image.item = item
                image.save()
            return HttpResponseRedirect(reverse('shopping:products'))
    return render(request, 'shopping/addproduct.html', {
        'form': form,
        'image_form': image_form
    })
@staff_member_required(login_url='/sign-in')
@login_required(login_url='/sign-in')
def update_product_view(request, id):
    product_instance = get_object_or_404(Item, pk=id)
    form = ItemCreationForm(request.POST or None, instance=product_instance)
    image_set = ItemImage.objects.filter(item=product_instance)
    ImageFormset = modelformset_factory(ItemImage, form=ImageForm, max_num=len(image_set))
    image_form = ImageFormset(request.POST or None, request.FILES or None, queryset=image_set)
    if form.is_valid() and image_form.is_valid():
        form.save()
        for form in image_form:
            form.save()
        return HttpResponseRedirect(reverse('shopping:products'))
    return render(request, 'shopping/updateproduct.html', {
        'item': product_instance,
        'form': form,
        'image_form': image_form
    })

@staff_member_required(login_url='/sign-in')
@login_required(login_url='/sign-in')
def update_order_view(request, id):
    order_instance = get_object_or_404(Order,pk=id)
    order_form = OrderCreationForm(request.POST or None, instance=order_instance)
    item_set = ItemOrder.objects.filter(order=order_instance)
    ItemOrderFormset = modelformset_factory(ItemOrder, form=ItemOrderForm, max_num=len(item_set))
    item_form = ItemOrderFormset(request.POST or None, queryset=item_set)
    if order_form.is_valid() and item_form.is_valid():
        order_form.save()
        for form in item_form:
            form.save()
        send_order_status_change_email(order=get_object_or_404(Order,pk=id))
        return HttpResponseRedirect(reverse('shopping:admin'))
    return render(request, 'shopping/updateorder.html', {
        'order': order_instance,
        'order_form': order_form,
        'item_form': item_form,
    })


@staff_member_required(login_url='/sign-in')
@login_required(login_url='/sign-in')
def add_order_view(request):
    order_form = OrderCreationForm()
    item_form = ItemFormset(queryset=ItemOrder.objects.none())
    if request.method == 'POST':
        order_form = OrderCreationForm(request.POST)
        item_form = ItemFormset(request.POST)
        if order_form.is_valid() and item_form.is_valid():
            order = order_form.save()
            for form in item_form:
                item = form.save(commit=False)
                item.order = order
                item.save()
                form.save_m2m()
            send_order_email(order.customer, order)
            return HttpResponseRedirect(reverse('shopping:admin'))

    return render(request, 'shopping/addorder.html', {
        'order_form': order_form,
        'item_form': item_form,
    })

@user_passes_test(lambda u: not (u.is_superuser or u.is_staff), login_url='/sign-in')
def category_view(request, category):

icingtales/shopping/templates/shopping/addflavor.html
{% extends 'shopping/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Add Flavor
{% endblock %}

{% block body %}
    <div class="container-sm p-2 mx-5">
        <form action="{% url 'shopping:addflavor' %}" method="post" class="form-group">
            {% csrf_token %}
            {% if message %}
                <div class="alert alert-danger">{{ message }}</div>
            {% endif %}
            <div class="container-fluid-sm">
                <h2 class= "text-info mt-3" >Create Flavor</h2>
            </div>
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

icingtales/shopping/templates/shopping/addtopping.html
{% extends 'shopping/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Add Topping
{% endblock %}

{% block body %}
    <div class="container-sm p-2 mx-5">
        <form action="{% url 'shopping:addtopping' %}" method="post" class="form-group">
            {% csrf_token %}
            {% if message %}
                <div class="alert alert-danger">{{ message }}</div>
            {% endif %}
            <div class="container-fluid-sm">
                <h2 class= "text-info mt-3" >Create Topping</h2>
            </div>
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Create</button>
        </form>
    </div>
{% endblock %}

icingtales/shopping/templates/shopping/admin.html
{% extends 'shopping/layout.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block body %}
    <div class = "container-fluid row my-4">
        <div class="col-sm-3">
            <div class="card border-primary p-3 h-100">
                <div class="card border-info shadow text-primary p-3 my-card" ><span class="fas fa-birthday-cake fa-lg" aria-hidden="true"></span></div>
                <div class="text-primary text-center mt-3"><h5>Total Orders</h5></div>
                <div class="text-primary text-center mt-2"><h5>{{ total_orders }}</h5></div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card border-info p-3 h-100">
                <div class="card border-info shadow text-info p-3 my-card" ><span class="fas fa-bell fa-lg" aria-hidden="true"></span></div>
                <div class="text-info text-center mt-3"><h5>Total Orders Today</h5></div>
                <div class="text-info text-center mt-2"><h3>{{ total_orders_today }}</h3></div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card border-success p-3 h-100">
                <div class="card border-success shadow text-success p-3 my-card" ><span class="fas fa-calendar-check fa-lg" aria-hidden="true"></span></div>
                <div class="text-success text-center mt-3"><h5>Total Orders Ready</h5></div>
                <div class="text-success text-center mt-2"><h3>{{ total_orders_ready }}</h3></div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card border-warning p-3 h-100">
                <div class="card border-danger shadow text-warning p-3 my-card" ><span class="fas fa-hourglass-start fa-lg" aria-hidden="true"></span></div>
                <div class="text-warning text-center mt-3"><h5>Total Orders Pending</h5></div>
                <div class="text-warning text-center mt-2"><h3>{{ total_orders_pending }}</h3></div>
            </div>
        </div>
    </div>

    <div class="container-fluid row">
        <div class="col-md-12 p-3">
            <div class="card border-primary p-3">
                <div class="inline-group">
                    <h4 class="text-primary" style="display:inline;">Orders </h4>
                    <a href= "{% url 'shopping:addorder' %}"><i class="fa fa-plus text-success"></i></a>
                </div>
                <h6 class="text-secondary">Filter</h6>
                <form class="form-inline" style="padding-bottom: 5px;">
                    <div class="row">
                        <div class="col-md-2">
                            <input id="id" class= "form-control" type="text" name="id" placeholder="Id">
                        </div>
                        <div class="col-md-2">
                            <input id="customer" class= "form-control" type="text" name="customer" placeholder="Customer">
                        </div>
                        <div class="col-md-2">
                            <input id="date" class= "form-control" type="text" name="date" placeholder="Date">
                        </div>
                        <div class="col-md-2">
                            <input id="time" class= "form-control" type="text" name="time" placeholder="Time">
                        </div>
                        <div class="col-md-2">
                            <input id="item" class= "form-control" type="text" name="Item" placeholder="Item">
                        </div>
                        <div class="col-md-2">
                            <input id="status" class= "form-control" type="text" name="status" placeholder="Status">
                        </div>
                    </div>
                </form>
                <div class="scrollable">
                    <table class="dashboard-table table table-striped table-hover">
                        <thead>
                            <th scope="col">Id</th>
                            <th scope="col">Customer</th>
                            <th scope="col">Contact</th>
                            <th scope="col">Order Date</th>
                            <th scope="col">Order Time</th>
                            <th scope="col">Items</th>
                            <th scope="col">Price</th>
                            <th scope="col">Status</th>
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                            <tr scope="row">
                                <td>{{ order.id }}</td>
                                <td>{{ order.customer.get_full_name }}</td>
                                <td>{{ order.customer.mobile_number }}</td>
                                <td>{{ order.date_created.date }}</td>
                                <td>{{ order.date_created.time }}</td>
                                <td>
                                    <ul style="padding-left:0px;margin:0px;list-style-type:none;">
                                        {% for item in order.order_items.all %}
                                            <li>{{ item.quantity }} {{ item.item.name }} (Topping: {{ item.topping }}, Flavor: {{ item.flavor }})</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td>${{ order.price }}</td>
                                <td>{{ order_status|get_item:order.status }}</td>
                                <td><div><a href="{% url 'shopping:updateorder' order.id %}" class="text-primary"><i class="fas fa-edit text-primary>" aria-hidden="true"></i> Update</a></div></td>
                                <td><div><a href="{% url 'shopping:deleteorder' order.id %}" class="text-danger"><i class="fas fa-trash text-danger>" aria-hidden="true"></i> Delete</a></div></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

icingtales/shopping/templates/shopping/category.html
{% extends 'shopping/layout.html' %}
{% load static %}
{% block title %}
    {{ category.capitalize }} Cakes
{% endblock %}
{% block body-class %}{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
            $('.cart').click(function () {
                let item_id = $(this).attr('data-id');
                let url = "{% url 'shopping:item' '1' %}".replace('1', item_id);
                console.log(url);
                $('.sure').attr('href', url);
            });
        });
    </script>
{% endblock %}
{% block body %}
    <div class="item-collection container-fluid">
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Want to customize your cake e.g., Add Topping or Change Flavor?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-footer">
                <a class="btn btn-danger no-thanks" href="" data-dismiss="modal">No thanks</a>
                <a class="btn btn-success sure" href=""> Sure </a>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
            <div class="w-100 item-collection-heading px-4">Our
                {% if category %}
                    {{ category.capitalize }} Cakes
                {% elif flavor %}
                    {{ flavor.capitalize }} Flavored Cakes
                {% elif topping %}
                     Cakes with {{ topping }} Topping
                {% elif flower %}
                    Cakes with {{ flower }} Flower
                {% endif %}
            </div>
            {% for item in items %}
                <div class="col">
                    <div class="product-card card border-info m-3">
                        <div class="card-title bg-info rounded d-flex justify-content-between p-1">
                            <h6 class="text-light mt-1 ml-2">{{ item.name }}</h6>
                            {% if item in top4_purchases %}
                                <img src="{% static 'shopping/images/best-seller.png' %}" class="tag mx-2"/>
                            {% endif %}
                            {% if item in new_items %}
                                <img src="{% static 'shopping/images/new.png' %}" class="tag mx-2"/>
                            {% endif %}
                        </div>
                        <div style="height:400px; width:400px;overflow:hidden; align-self: center;">
                            <img class="card-img img-responsive" src="{{ item.item_images.first.image.url }}" alt="{{ item.item_images.first.alt_image }}">
                        </div>
                        <div class="card-body text-secondary">{{ item.description }}</div>
                        <div class="buy d-flex justify-content-between align-items-center px-3 py-2">
                            <div class="price text-success"><h6 class="mt-2">${{ item.price }}</h6></div>
                            <a {% if not request.user.is_authenticated %} href="{% url 'shopping:signin' %}" {% else %} href="" data-toggle="modal" data-target="#exampleModalCenter" data-id="{{ item.id }}"{% endif %} class="btn btn-info my-2 cart"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
                            <a href="{% url 'shopping:item' item.id %}" class="btn btn-info my-2"><i class="fas fa-search"></i> View Item</a>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
                    <div class="w-100"></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

icingtales/shopping/templates/shopping/flavors.html
{% extends 'shopping/layout.html' %}

{% block title %}
    Flavors
{% endblock %}

{% block body %}
    <div class="container-fluid row">
        <div class="col-md-12 p-3">
            <div class="card border-primary p-3">
                <div class="inline-group">
                    <h4 class="text-primary" style="display:inline;">Flavors </h4>
                    <a href= "{% url 'shopping:addflavor' %}"><i class="fa fa-plus text-success"></i></a>
                </div>
                <div class="scrollable">
                    <table class="dashboard-table table table-striped table-hover">
                        <thead>
                            <th scope="col">Id</th>
                            <th scope="col">Flavor Name</th>
                            <th scope="col">Surcharge</th>
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        </thead>
                        <tbody>
                        {% for flavor in flavors %}
                            <tr scope="row">
                                <td>{{ flavor.id }}</td>
                                <td>{{ flavor.name }}</td>
                                <td>${{ flavor.surcharge }}</td>
                                <td><div><a href="{% url 'shopping:updateflavor' flavor.id %}" class="text-primary"><i class="fas fa-edit text-primary>" aria-hidden="true"></i> Update</a></div></td>
                                <td><div><a href="" class="text-danger"><i class="fas fa-trash text-danger>" aria-hidden="true"></i> Delete</a></div></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

icingtales/shopping/templates/shopping/flowers.html
{% extends 'shopping/layout.html' %}

{% block title %}
    Flowers
{% endblock %}

{% block body %}
    <div class="container-fluid row">
        <div class="col-md-12 p-3">
            <div class="card border-primary p-3">
                <div class="inline-group">
                    <h4 class="text-primary" style="display:inline;">Flowers </h4>
                    <a href= "{% url 'shopping:addflower' %}"><i class="fa fa-plus text-success"></i></a>
                </div>
                <div class="scrollable">
                    <table class="dashboard-table table table-striped table-hover">
                        <thead>
                            <th scope="col">Id</th>
                            <th scope="col">Flower Name</th>
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        </thead>
                        <tbody>
                        {% for flower in flowers %}
                            <tr scope="row">
                                <td>{{ flower.id }}</td>
                                <td>{{ flower.name }}</td>
                                <td><div><a href="{% url 'shopping:updateflower' flower.id %}" class="text-primary"><i class="fas fa-edit text-primary>" aria-hidden="true"></i> Update</a></div></td>
                                <td><div><a href="" class="text-danger"><i class="fas fa-trash text-danger>" aria-hidden="true"></i> Delete</a></div></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

icingtales/shopping/templates/shopping/signin.html
{% extends 'shopping/layout.html' %}
{% load static %}
{% block title %}
    Sign In
{% endblock %}
{% block body-class %}{% endblock %}
{% block body %}
    <div class="sign-in container-sm p-1 bg-light">

        <form action="{% url 'shopping:signin' %}" method="post" class="form-signin">
            {% csrf_token %}
            {% if message %}
                <div class="alert alert-danger text-center">{{ message }}</div>
            {% endif %}
            <div class="container d-flex justify-content-center align-top">
                <img src="{% static 'shopping/images/logo.png' %}" style="width:200px;">
            </div>

            <h2 class="mb-3 font-weight-normal text-center">Please sign in</h2>
            {{ form }}
            <div class="checkbox mb-1 text-center">
                <label>
                    <input type="checkbox" value="remember-me" name="remember"> Remember me
                </label>
            </div>
            <div class="text-center form-description mb-2">
                <a href="">Forgot Email/Password</a>
            </div>
            <div class="text-center form-description text-muted mb-2">
                Don't have and account? <a href="{% url 'shopping:register' %}">Sign Up</a>
            </div>
            <button class="btn btn-primary btn-block" type="submit">Sign In</button>

        </form>
    </div>
{% endblock %}

icingtales/shopping/templates/shopping/updateflavor.html
{% extends 'shopping/layout.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Update Flavor
{% endblock %}

{% block body %}
    <div class="container-sm p-2 mx-5">
        <form action="{% url 'shopping:updateflavor' flavor.id %}" method="post" class="form-group">
            {% csrf_token %}
            {% if message %}
                <div class="alert alert-danger">{{ message }}</div>
            {% endif %}
            <div class="container-fluid-sm">
                <h2 class= "text-info mt-3" >Update Flavor</h2>
            </div>
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
    </div>
{% endblock %}

icingtales/shopping/templates/shopping/users.html
{% extends 'shopping/layout.html' %}

{% block title %}
    Users
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="container-sm alert-primary rounded p-3 my-3">Customers go here</div>
    </div>

{% endblock %}